"""be_civic_dossier.codegen — render.py codegen + template loader.

Two responsibilities:

1. Resolve and load the bundled Jinja2-style HTML templates from the plugin at
   ``${CLAUDE_PLUGIN_ROOT}/skills/bc-dossier-compilation/templates/``. A project-
   local copy under ``<user-project>/<procedure-id>/dossier/templates/`` takes
   precedence — that's the agent-edit / user-edit escape hatch.

2. Generate (and refresh) the ``render.py`` script the agent writes into the
   user's project folder.

The actual PDF rendering lives in sibling modules under ``be_civic_dossier``
(Dossier, IdCard, FullPageCert, MultiPageDoc, FeeReceipt, FilledForm,
Placeholder, watermark).

This module is dependency-free at import time: it works whether or not the rest
of ``be_civic_dossier`` is present, so the codegen path is robust to partial
installs.
"""

from __future__ import annotations

import ast
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional


# ---------------------------------------------------------------------------
# Template resolution
# ---------------------------------------------------------------------------

#: Template filenames bundled under the plugin's
#: ``skills/bc-dossier-compilation/templates/`` directory.
TEMPLATE_FILENAMES = (
    "cover.html",
    "checklist.html",
    "divider.html",
    "placeholder.html",
    "filled-form-annexe-1.html",
    "officer-notes.html",
)


def plugin_root() -> Path:
    """Return the plugin's root directory.

    Resolution order:
      1. ``CLAUDE_PLUGIN_ROOT`` env var (set by the Cowork harness).
      2. Walk upward from this file looking for a ``.claude-plugin/plugin.json``
         marker — works when the package is imported in-place from the plugin
         tree, e.g. during dev.

    Raises ``RuntimeError`` if neither resolution succeeds.
    """
    env = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        return Path(env).expanduser().resolve()

    here = Path(__file__).resolve()
    for ancestor in (here, *here.parents):
        marker = ancestor / ".claude-plugin" / "plugin.json"
        if marker.is_file():
            return ancestor

    raise RuntimeError(
        "Could not resolve plugin root. Set CLAUDE_PLUGIN_ROOT or import this "
        "module from inside a checkout of be-civic-plugin."
    )


def bundled_templates_dir() -> Path:
    """Path to the plugin-bundled templates folder."""
    return plugin_root() / "skills" / "bc-dossier-compilation" / "templates"


def resolve_template(name: str, project_templates_dir: Optional[Path] = None) -> Path:
    """Return the on-disk path to a template.

    Prefers a project-local override at ``<project_templates_dir>/<name>``;
    falls back to the plugin-bundled copy. Raises ``FileNotFoundError`` if
    neither exists.
    """
    if name not in TEMPLATE_FILENAMES:
        raise ValueError(
            f"Unknown template {name!r}. Known templates: {TEMPLATE_FILENAMES}"
        )

    if project_templates_dir is not None:
        local = Path(project_templates_dir) / name
        if local.is_file():
            return local

    bundled = bundled_templates_dir() / name
    if not bundled.is_file():
        raise FileNotFoundError(
            f"Template {name!r} not found at {bundled} and no project-local "
            "override supplied."
        )
    return bundled


def load_template(name: str, project_templates_dir: Optional[Path] = None) -> str:
    """Return the raw HTML text of a template."""
    return resolve_template(name, project_templates_dir).read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# render.py codegen
# ---------------------------------------------------------------------------

#: Header text written at the top of every generated ``render.py``.
RENDER_PY_HEADER_TEMPLATE = '''"""Be Civic dossier renderer for {procedure_id}.

Generated by the be-civic-plugin agent. Edit and re-run to regenerate.

    python3 render.py

Re-running with the same documents/ folder produces an identical PDF (the
filename embeds the rendered-on date so each run lands in its own file).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Plugin path injection — auto-generated, do not edit by hand.
# ---------------------------------------------------------------------------
# Three-tier resolution so this script keeps working as the plugin moves on
# disk: (1) the absolute path baked in at generation time, (2) the
# CLAUDE_PLUGIN_ROOT env var if the script is re-run under the Cowork harness,
# (3) a "regen this header" error message that tells the agent what to do.

_PLUGIN_ROOT_BAKED = r"{plugin_root_abs}"


def _resolve_plugin_root() -> Path:
    candidates = []
    env = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        candidates.append(Path(env).expanduser())
    candidates.append(Path(_PLUGIN_ROOT_BAKED))
    for candidate in candidates:
        if candidate.is_dir() and (candidate / "scripts" / "be_civic_dossier").is_dir():
            return candidate.resolve()
    raise RuntimeError(
        "Could not locate the be-civic-plugin install. Try one of:\\n"
        "  - set CLAUDE_PLUGIN_ROOT to the plugin checkout path\\n"
        "  - re-run the dossier compilation skill so the agent regenerates this\\n"
        "    file's import header with the new plugin path"
    )


_PLUGIN_ROOT = _resolve_plugin_root()
sys.path.insert(0, str(_PLUGIN_ROOT / "vendor"))
sys.path.insert(0, str(_PLUGIN_ROOT / "scripts"))

try:
    from be_civic_dossier import (
        Dossier,
        IdCard,
        FullPageCert,
        MultiPageDoc,
        FeeReceipt,
        FilledForm,
        Placeholder,
    )
except ImportError as exc:  # pragma: no cover - probe path
    raise RuntimeError(
        f"Failed to import be_civic_dossier from {{_PLUGIN_ROOT}}: {{exc}}. "
        "Re-run the dossier compilation skill so the agent regenerates this "
        "file's import header with a working plugin path."
    ) from exc

# ---------------------------------------------------------------------------
# Dossier definition — edit freely. The agent regenerates the item list on
# refresh, but preserves the surrounding Dossier(...) constructor call and any
# .add(...) lines the user has added manually.
# ---------------------------------------------------------------------------
'''


#: Marker comment lines that bracket the agent-managed item list inside
#: ``render.py``. Anything between these markers is rewritten on refresh; the
#: surrounding ``Dossier(...)`` constructor, ``add_officer_notes(...)``, and
#: ``render(...)`` call are preserved.
ITEMS_BEGIN = "# BEGIN agent-managed items -- regenerated on refresh"
ITEMS_END = "# END agent-managed items"


@dataclass
class DossierConfig:
    """Inputs the codegen needs to write a render.py for the first time.

    ``items_source`` is the multi-line body that goes between the BEGIN/END
    agent-managed-items markers. The lines must be at **module level** (no
    leading indentation) because the markers sit at module level. Use a raw
    triple-quoted block like::

        items_source = (
            'd.add(FullPageCert("../documents/birth.pdf",\\n'
            '                   cert_type="Birth certificate",\\n'
            '                   original_required=True))\\n'
            'd.add(Placeholder(cert_type="Annexe 1", source="commune visit"))'
        )

    Empty / whitespace-only ``items_source`` falls back to a no-items comment.
    """

    procedure_id: str
    procedure_title: str
    conversation_language: str
    filing_language: str
    applicant_name: str
    filing_authority: str
    filing_date: str
    output_filename: str  # e.g. "dossier-2026-05-19.pdf"
    items_source: str = ""  # multi-line "d.add(...)" body, no leading indent
    officer_notes_path: str = "officer-notes.md"


def render_render_py(config: DossierConfig, plugin_root_abs: Optional[Path] = None) -> str:
    """Return the full text of a fresh ``render.py`` for this dossier.

    ``plugin_root_abs`` overrides the auto-detected plugin path — useful for
    tests or when generating a render.py from a context that isn't inside the
    plugin checkout.
    """
    root = (plugin_root_abs or plugin_root()).resolve()
    header = RENDER_PY_HEADER_TEMPLATE.format(
        procedure_id=config.procedure_id,
        plugin_root_abs=str(root),
    )

    raw = config.items_source.strip("\n")
    if raw:
        # Dedent the whole block so the items land at module level (the
        # marker comments sit at module scope). textwrap.dedent preserves
        # relative indentation inside multi-line ``d.add(\n   ...)`` calls.
        import textwrap

        items_body = textwrap.dedent(raw).rstrip()
    else:
        items_body = "# (no items yet — fill in via Step 3 of bc-dossier-compilation)"

    body = (
        f"d = Dossier(\n"
        f"    procedure_id={config.procedure_id!r},\n"
        f"    procedure_title={config.procedure_title!r},\n"
        f"    conversation_language={config.conversation_language!r},\n"
        f"    filing_language={config.filing_language!r},\n"
        f"    applicant_name={config.applicant_name!r},\n"
        f"    filing_authority={config.filing_authority!r},\n"
        f"    filing_date={config.filing_date!r},\n"
        f")\n\n"
        f"{ITEMS_BEGIN}\n"
        f"{items_body}\n"
        f"{ITEMS_END}\n\n"
        f"officer_notes_path = Path(__file__).parent / {config.officer_notes_path!r}\n"
        f"if officer_notes_path.is_file():\n"
        f"    d.add_officer_notes(officer_notes_path.read_text(encoding=\"utf-8\"))\n\n"
        f"if __name__ == \"__main__\":\n"
        f"    out = d.render(output_path={config.output_filename!r})\n"
        f"    print(f\"Wrote {{out}}\")\n"
    )

    return header + body


# ---------------------------------------------------------------------------
# Refresh — preserve user edits, only modify the item list
# ---------------------------------------------------------------------------

_ITEMS_BLOCK_RE = re.compile(
    re.escape(ITEMS_BEGIN) + r".*?" + re.escape(ITEMS_END),
    flags=re.DOTALL,
)


def refresh_items(existing_source: str, new_items_source: str) -> str:
    """Rewrite the agent-managed item list inside an existing ``render.py``.

    Strategy:

    * If the file carries our ``BEGIN/END agent-managed items`` markers, we
      replace the block between them. Everything outside the markers — header,
      ``Dossier(...)`` constructor, officer-notes block, ``__main__`` block,
      and any user-added ``d.add(...)`` lines outside the markers — is
      preserved verbatim.
    * If the markers are absent (e.g. the user rewrote the file by hand), we
      raise so the caller can decide whether to rewrite the whole file or skip
      the refresh.

    The new items block always carries a trailing newline so the surrounding
    code keeps its blank-line separation.
    """
    if not _ITEMS_BLOCK_RE.search(existing_source):
        raise ValueError(
            "render.py is missing the agent-managed item-list markers "
            f"({ITEMS_BEGIN!r} / {ITEMS_END!r}). Refusing to rewrite — the file "
            "may have been hand-edited. Regenerate from scratch if that's what "
            "you want."
        )

    block = f"{ITEMS_BEGIN}\n{new_items_source.strip(chr(10))}\n{ITEMS_END}"
    return _ITEMS_BLOCK_RE.sub(block, existing_source, count=1)


# ---------------------------------------------------------------------------
# Sanity probe — used by the agent's reconcile step to read existing items
# ---------------------------------------------------------------------------


@dataclass
class ParsedItem:
    """Lightweight view of one ``d.add(...)`` call inside an existing render.py."""

    class_name: str  # IdCard, FullPageCert, ...
    args: List[str]
    kwargs: dict


def parse_existing_items(source: str) -> Iterable[ParsedItem]:
    """Yield each ``d.add(SomeClass(...))`` from an existing render.py.

    Best-effort: ignores anything that doesn't parse cleanly. The agent should
    treat this as advisory — if a refresh disagrees with what the parser sees,
    re-read the file from disk and prompt the user.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return

    known_classes = {
        "IdCard",
        "FullPageCert",
        "MultiPageDoc",
        "FeeReceipt",
        "FilledForm",
        "Placeholder",
    }

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if not isinstance(node.func, ast.Attribute):
            continue
        if node.func.attr != "add":
            continue
        if len(node.args) != 1:
            continue
        inner = node.args[0]
        if not isinstance(inner, ast.Call):
            continue
        if not isinstance(inner.func, ast.Name):
            continue
        if inner.func.id not in known_classes:
            continue

        args: List[str] = []
        for arg in inner.args:
            try:
                args.append(ast.literal_eval(arg))
            except (ValueError, SyntaxError):
                args.append(ast.unparse(arg))

        kwargs: dict = {}
        for kw in inner.keywords:
            if kw.arg is None:  # **kwargs splat, skip
                continue
            try:
                kwargs[kw.arg] = ast.literal_eval(kw.value)
            except (ValueError, SyntaxError):
                kwargs[kw.arg] = ast.unparse(kw.value)

        yield ParsedItem(class_name=inner.func.id, args=args, kwargs=kwargs)


__all__ = (
    "TEMPLATE_FILENAMES",
    "plugin_root",
    "bundled_templates_dir",
    "resolve_template",
    "load_template",
    "DossierConfig",
    "render_render_py",
    "refresh_items",
    "parse_existing_items",
    "ParsedItem",
    "ITEMS_BEGIN",
    "ITEMS_END",
)
