"""be_civic_dossier.layouts.placeholder — "TO COLLECT" placeholder page.

Used for checklist items the user hasn't provided yet. The page is a
single A4 portrait page generated by Be Civic — it carries our branding
(cover-style) because the user looks at it and an officer never does
(the user replaces these before filing).

Visual reference: ``skills/bc-dossier-compilation/templates/placeholder.html``.

Placeholders are the "TO COLLECT — [name]. Source:
[path-id or commune-visit instructions]." class.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List

from .. import metadata


@dataclass
class Placeholder:
    """Item-class for a missing checklist row.

    :param cert_type: human-readable name of the item, e.g.
        "Annexe 1 — Déclaration de nationalité (signed at commune)".
    :param source: where the user obtains the item, e.g.
        "commune visit" or path-id like "nationality-pre-flight".
    """

    cert_type: str
    source: str
    # ``original_required`` is always False for a placeholder (there's nothing
    # to file yet). Kept as a field for parity with other item classes.
    original_required: bool = False

    # Class label used by the dossier renderer.
    layout_class: str = "placeholder"

    def render_pages(self, pdf) -> None:
        """Append a single placeholder page to ``pdf``."""
        _add_placeholder_page(pdf, cert_type=self.cert_type, source=self.source)


def _add_placeholder_page(pdf, *, cert_type: str, source: str) -> None:
    prev_auto = pdf.auto_page_break
    prev_bmargin = pdf.b_margin
    pdf.set_auto_page_break(auto=False)
    pdf.add_page()
    page_w = pdf.w
    page_h = pdf.h
    margin = 18

    # ---- top eyebrow stripe — muted grey to make the placeholder feel
    # different from filed documents
    pdf.set_fill_color(*metadata.BRAND["hairline"].as_tuple())
    pdf.rect(0, 0, page_w, 6, style="F")

    # ---- centered "TO COLLECT" badge
    badge_y = page_h * 0.22
    pdf.set_xy(margin, badge_y)
    pdf.set_text_color(*metadata.BRAND["mute"].as_tuple())
    pdf.set_font("Inter", "B", 28)
    pdf.cell(page_w - 2 * margin, 12, "TO COLLECT", align="C")

    # ---- item name (large)
    name_y = badge_y + 22
    pdf.set_xy(margin, name_y)
    pdf.set_text_color(*metadata.BRAND["ink"].as_tuple())
    pdf.set_font("Inter", "B", 22)
    pdf.multi_cell(page_w - 2 * margin, 10, cert_type, align="C")

    # ---- source line ("Source: ...")
    pdf.set_y(pdf.get_y() + 12)
    pdf.set_x(margin)
    pdf.set_text_color(*metadata.BRAND["mute"].as_tuple())
    pdf.set_font("SourceSansPro", "", 11)
    pdf.cell(page_w - 2 * margin, 6, "WHERE TO GET IT", align="C")

    pdf.set_y(pdf.get_y() + 6)
    pdf.set_x(margin)
    pdf.set_text_color(*metadata.BRAND["ink_body"].as_tuple())
    pdf.set_font("SourceSansPro", "B", 13)
    pdf.multi_cell(page_w - 2 * margin, 6, source or "—", align="C")

    # ---- gold rule near the bottom + reminder
    bottom_y = page_h - 40
    pdf.set_fill_color(*metadata.BRAND["gold"].as_tuple())
    pdf.rect(margin, bottom_y, page_w - 2 * margin, 1.2, style="F")

    pdf.set_xy(margin, bottom_y + 6)
    pdf.set_text_color(*metadata.BRAND["mute"].as_tuple())
    pdf.set_font("SourceSansPro", "", 10)
    msg = (
        "Replace this placeholder with the actual document, then "
        "regenerate the dossier (re-run render.py)."
    )
    pdf.multi_cell(page_w - 2 * margin, 5, msg, align="C")

    pdf.set_auto_page_break(auto=prev_auto, margin=prev_bmargin)
